SHOW ACCESS;
SHOW CHANGED SETTINGS ILIKE '%MEMORY%';
SHOW CHANGED SETTINGS ILIKE '%MEMORY%';
SHOW CLUSTER 'test_shard_localhost' FORMAT Vertical;
SHOW CLUSTERS LIKE 'test%' LIMIT 1;
SHOW CLUSTERS;
SHOW COLUMNS FROM `orders` LIKE 'delivery_%';
SHOW COLUMNS FROM `$4@^7`;
SHOW COLUMNS FROM `'` FROM `'`;
SHOW COLUMNS FROM `'`.`'`;
SHOW COLUMNS FROM database_123456789abcde.tab;
SHOW COLUMNS FROM `NULL`;
SHOW COLUMNS FROM tab FROM database_123456789abcde;
SHOW COLUMNS FROM tab ILIKE '%INT%';
SHOW COLUMNS FROM tab LIKE '%int%';
SHOW COLUMNS FROM tab LIMIT 1;
SHOW COLUMNS FROM tab NOT ILIKE '%INT%';
SHOW COLUMNS FROM tab NOT LIKE '%int%';
SHOW COLUMNS FROM tab WHERE field LIKE '%int%';
SHOW COLUMNS FROM tab;
SHOW CREATE buffer;
SHOW CREATE check_comments;
show create data_02230_column_ttl format TSVRaw;
show create data_02230_ttl format TSVRaw;
SHOW CREATE DATABASE INFORMATION_SCHEMA;
SHOW CREATE DATABASE memory_01069;
SHOW CREATE DATABASE replicated_database_params;
SHOW CREATE DATABASE t_2710_db;
SHOW CREATE DATABASE test_01155_atomic;
SHOW CREATE dict;
SHOW CREATE DICTIONARY dictionary_with_comment;
SHOW CREATE DICTIONARY db_01018.dict1;
SHOW CREATE DICTIONARY db_for_dict.dict_with_hashed_layout;
SHOW CREATE DICTIONARY memory_db.dict2;
SHOW CREATE DICTIONARY sqllt.dictionary FORMAT Null;
SHOW CREATE distributed;
SHOW CREATE distributed_tf;
SHOW CREATE file;
show create foo;
SHOW CREATE INFORMATION_SCHEMA.COLUMNS;
SHOW CREATE log1;
SHOW CREATE log;
SHOW CREATE mem;
SHOW CREATE merge;
SHOW CREATE merge_tf;
show create mv;
show create my_view;
SHOW CREATE nested_table;
show create null_02230_ttl format TSVRaw;
SHOW CREATE POLICY db1_02703 ON db1_02703.*;
SHOW CREATE POLICY db2_02703 ON *;
SHOW CREATE POLICY ON db1_02703.*;
SHOW CREATE POLICY ON db1_02703.`*`;
SHOW CREATE POLICY p1_01295 ON db.table;
SHOW CREATE POLICY p2_01295 ON db.table;
SHOW CREATE POLICY p1_01296 ON db_01296.table;
SHOW CREATE POLICY p1_01296 ON table;
SHOW CREATE POLICY p2_01295 ON db.table;
SHOW CREATE POLICY p2_01296 ON db_01296.table;
SHOW CREATE POLICY p2_01296 ON table;
SHOW CREATE POLICY p3_01295 ON db.table, db2.table2;
SHOW CREATE POLICY p3_01295 ON db.table;
SHOW CREATE POLICY p3_01296 ON db_01296.table2;
SHOW CREATE POLICY p3_01296 ON db_01296.table;
SHOW CREATE POLICY p3_01296 ON table2;
SHOW CREATE POLICY p3_01296 ON table;
SHOW CREATE POLICY p4_01295 ON db.table;
SHOW CREATE POLICY p4_01295 ON db.table;
SHOW CREATE POLICY p4_01296 ON db_01296.table;
SHOW CREATE POLICY p4_01296 ON table;
SHOW CREATE POLICY p5_01295 ON db.table;
SHOW CREATE POLICY p5_01296 ON db_01296.table2;
SHOW CREATE POLICY p5_01296 ON table2;
SHOW CREATE POLICY p6_01295 ON db.table;
SHOW CREATE POLICY p7_01295 ON db.table;
SHOW CREATE POLICY sqllt_policy FORMAT Null;
SHOW CREATE PROFILE s10_01294;
SHOW CREATE PROFILE s1_01294, s2_01294, s3_01294, s4_01294;
SHOW CREATE PROFILE s1_01294;
SHOW CREATE PROFILE s2_01294;
SHOW CREATE PROFILE s3_01294;
SHOW CREATE PROFILE s4_01294;
SHOW CREATE PROFILE s5_01294;
SHOW CREATE PROFILE s6_01294;
SHOW CREATE PROFILE s7_01294;
SHOW CREATE PROFILE s8_01294;
SHOW CREATE PROFILE s9_01294;
SHOW CREATE QUOTA default;
SHOW CREATE QUOTA q10_01297;
SHOW CREATE QUOTA q11_01297;
SHOW CREATE QUOTA q12_01297;
SHOW CREATE QUOTA q13_01297;
SHOW CREATE QUOTA q14_01297;
SHOW CREATE QUOTA q15_01297;
SHOW CREATE QUOTA q16_01297;
SHOW CREATE QUOTA q1_01297, q2_01297;
SHOW CREATE QUOTA q1_01297;
SHOW CREATE QUOTA q2_01297;
SHOW CREATE QUOTA q3_01297;
SHOW CREATE QUOTA q4_01297;
SHOW CREATE QUOTA q5_01297;
SHOW CREATE QUOTA q6_01297;
SHOW CREATE QUOTA q7_01297;
SHOW CREATE QUOTA q8_01297;
SHOW CREATE QUOTA q9_01297;
SHOW CREATE QUOTA sqllt_quota FORMAT Null;
SHOW CREATE rich_syntax;
SHOW CREATE ROLE `r2_01293@%.myhost.com`;
SHOW CREATE ROLE r1_01293, r2_01293;
SHOW CREATE ROLE r1_01293;
SHOW CREATE ROLE sqllt_role FORMAT Null;
SHOW CREATE ROW POLICY p1_01295 ON db.table;
SHOW CREATE ROW POLICY sqllt_row_policy FORMAT Null;
SHOW CREATE sales;
SHOW CREATE SETTINGS PROFILE s3_01294;
SHOW CREATE SETTINGS PROFILE sqllt_settings_profile FORMAT Null;
SHOW CREATE t;
SHOW CREATE t_2710_show_table;
show create t_l5ydey;
SHOW CREATE t_merge;
SHOW CREATE TABLE add_table;
show create table aggregate_function_combinators format TSVRaw;
show create table alter_ttl;
show create table asynchronous_inserts format TSVRaw;
SHOW CREATE TABLE BannerDict;
SHOW CREATE TABLE bloom_filter_idx_good;
show create table build_options format TSVRaw;
SHOW CREATE TABLE cannot_be_nullable;
SHOW CREATE TABLE cast FORMAT TSVRaw;
SHOW CREATE TABLE cast1 FORMAT TSVRaw;
SHOW CREATE TABLE check_query_comment_column;
show create table child2;
show create table child3;
show create table child;
show create table clusters format TSVRaw;
SHOW CREATE TABLE codecs10;
SHOW CREATE TABLE codecs11;
SHOW CREATE TABLE codecs1;
SHOW CREATE TABLE codecs2;
SHOW CREATE TABLE codecs3;
SHOW CREATE TABLE codecs4;
SHOW CREATE TABLE codecs5;
SHOW CREATE TABLE codecs6;
SHOW CREATE TABLE codecs7;
SHOW CREATE TABLE codecs8;
SHOW CREATE TABLE codecs9;
show create table collations format TSVRaw;
show create table columns format TSVRaw;
SHOW CREATE TABLE columns_with_multiple_streams;
SHOW CREATE TABLE columns_with_multiple_streams_compact;
SHOW CREATE TABLE compress_table;
SHOW CREATE TABLE compression_codec;
SHOW CREATE TABLE compression_codec_log;
SHOW CREATE TABLE compression_codec_multiple_log;
SHOW CREATE TABLE compression_codec_multiple_more_types;
SHOW CREATE TABLE compression_codec_multiple_more_types_replicated;
SHOW CREATE TABLE compression_codec_multiple_tiny_log;
SHOW CREATE TABLE compression_codec_tiny_log;
SHOW CREATE TABLE constrained2;
SHOW CREATE TABLE constrained;
show create table contributors format TSVRaw;
show create table current_roles format TSVRaw;
SHOW CREATE TABLE data_null;
show create table data_skipping_indices format TSVRaw;
show create table data_type_families format TSVRaw;
show create table databases format TSVRaw;
SHOW CREATE TABLE default_table;
SHOW CREATE TABLE defaults_on_defaults;
SHOW CREATE TABLE dep2;
SHOW CREATE TABLE dep;
show create table detached_parts format TSVRaw;
SHOW CREATE TABLE dict_db_01224.dict FORMAT TSVRaw;
SHOW CREATE TABLE dict_db_01224_dictionary.`dict_db_01224.dict` FORMAT TSVRaw;
SHOW CREATE TABLE dict_db_01225_dictionary.`dict_db_01225.dict` FORMAT TSVRaw;
SHOW CREATE TABLE dict_db_01225_dictionary.`dict_db_01225.no_such_dict`;
show create table dictionaries format TSVRaw;
show create table disks format TSVRaw;
SHOW CREATE TABLE dist_tbl;
show create table distributed_ddl_queue format TSVRaw;
show create table distribution_queue format TSVRaw;
show create table enabled_roles format TSVRaw;
show create table errors format TSVRaw;
show create table events format TSVRaw;
show create table formats format TSVRaw;
show create table functions format TSVRaw;
SHOW CREATE TABLE imdb_01148.anything;
SHOW CREATE TABLE kek;
show create table licenses format TSVRaw;
SHOW CREATE TABLE log;
SHOW CREATE TABLE lol;
show create table macros format TSVRaw;
SHOW CREATE TABLE mem;
SHOW CREATE TABLE memory_01069.mt;
show create table merge;
show create table merge_distributed;
SHOW CREATE TABLE merge_tree_pk;
SHOW CREATE TABLE merge_tree_pk_sql;
show create table merge_tree_settings format TSVRaw;
show create table merges format TSVRaw;
show create table metrics format TSVRaw;
SHOW CREATE TABLE minmax_idx2;
SHOW CREATE TABLE minmax_idx2_r;
SHOW CREATE TABLE minmax_idx;
SHOW CREATE TABLE minmax_idx_r;
show create table moves format TSVRaw;
SHOW CREATE TABLE mt2;
SHOW CREATE TABLE mt;
show create table mt_compact;
SHOW CREATE TABLE multiword_types;
show create table mutations format TSVRaw;
SHOW CREATE TABLE mv;
SHOW CREATE TABLE no_prop_table;
SHOW CREATE TABLE non_metadata_alters;
show create table numbers format TSVRaw;
SHOW CREATE TABLE numbers1;
SHOW CREATE TABLE numbers2;
SHOW CREATE TABLE numbers3;
show create table numbers_mt format TSVRaw;
show create table one format TSVRaw;
show create table part_moves_between_shards format TSVRaw;
show create table parts format TSVRaw;
show create table parts_columns format TSVRaw;
SHOW CREATE TABLE pipe;
show create table projection_parts format TSVRaw;
show create table projection_parts_columns format TSVRaw;
SHOW CREATE TABLE prop_table;
show create table quota_limits format TSVRaw;
show create table quota_usage format TSVRaw;
show create table quotas format TSVRaw;
show create table quotas_usage format TSVRaw;
SHOW CREATE TABLE r_no_prop_table;
SHOW CREATE TABLE r_prop_table1;
SHOW CREATE TABLE r_prop_table2;
SHOW CREATE TABLE recompression_table;
SHOW CREATE TABLE rename_table;
SHOW CREATE TABLE rename_table_multiple;
SHOW CREATE TABLE rename_table_multiple_compact;
SHOW CREATE TABLE rename_table_polymorphic;
show create table replicas format TSVRaw;
SHOW CREATE TABLE replicated_alter1;
SHOW CREATE TABLE replicated_alter2;
show create table replicated_fetches format TSVRaw;
SHOW CREATE TABLE replicated_merge_tree_pk_sql;
show create table replicated_merge_tree_settings format TSVRaw;
SHOW CREATE TABLE replicated_mutations_empty_partitions;
SHOW CREATE TABLE replicated_table_for_alter1;
SHOW CREATE TABLE replicated_table_for_alter2;
SHOW CREATE TABLE replicated_table_for_reset_setting1;
SHOW CREATE TABLE replicated_table_for_reset_setting2;
show create table replication_queue format TSVRaw;
SHOW CREATE TABLE rmt1;
SHOW CREATE TABLE rmt;
show create table role_grants format TSVRaw;
show create table roles format TSVRaw;
show create table row_policies format TSVRaw;
SHOW CREATE TABLE set_null;
show create table settings format TSVRaw;
show create table settings_profile_elements format TSVRaw;
show create table settings_profiles format TSVRaw;
SHOW CREATE TABLE shard_0.demo_loan_01568;
SHOW CREATE TABLE shard_1.demo_loan_01568;
SHOW CREATE TABLE sqllt.table FORMAT Null;
show create table stack_trace format TSVRaw;
show create table storage_policies format TSVRaw;
SHOW CREATE TABLE summing;
SHOW CREATE TABLE summing_r2;
show create table t1;
SHOW CREATE TABLE t1;
SHOW CREATE TABLE t2;
SHOW CREATE TABLE t;
show create table t;
SHOW CREATE TABLE t_2710_show_table;
show create table t_index;
show create table t_index_replica;
SHOW CREATE TABLE t_nested_detach;
SHOW CREATE TABLE t_remove_sample_by;
SHOW CREATE TABLE t_ttl_move_if_exists;
SHOW CREATE TABLE t_tuple_numeric;
SHOW CREATE TABLE table;
SHOW CREATE TABLE table_02184;
show create table table_engines format TSVRaw;
SHOW CREATE TABLE table_for_alter;
SHOW CREATE TABLE table_for_rename1;
SHOW CREATE TABLE table_for_rename;
SHOW CREATE TABLE table_for_rename_nested;
SHOW CREATE TABLE table_for_reset_setting;
SHOW CREATE TABLE table_from_numbers;
SHOW CREATE TABLE table_from_remote;
SHOW CREATE TABLE table_from_select;
show create table table_functions format TSVRaw;
SHOW CREATE TABLE table_rename_with_default;
SHOW CREATE TABLE table_rename_with_ttl;
SHOW CREATE TABLE table_with_column_ttl;
SHOW CREATE TABLE table_with_lc_key;
SHOW CREATE TABLE table_with_string_key;
SHOW CREATE TABLE table_with_version;
SHOW CREATE TABLE table_with_version_replicated_1;
SHOW CREATE TABLE table_with_version_replicated_2;
show create table tables format TSVRaw;
SHOW CREATE TABLE test1601_detach_permanently_atomic.test_name_reuse FORMAT Vertical;
SHOW CREATE TABLE test1601_detach_permanently_lazy.test_name_reuse FORMAT Vertical;
SHOW CREATE TABLE test1601_detach_permanently_ordinary.test_name_reuse FORMAT Vertical;
SHOW CREATE TABLE test;
SHOW CREATE TABLE test_01048.`.inner.wv`;
SHOW CREATE TABLE test_01148_atomic.rmt2;
SHOW CREATE TABLE test_01148_atomic.rmt3;
SHOW CREATE TABLE test_01457.tf_merge;
SHOW CREATE TABLE test_01457.tf_numbers;
SHOW CREATE TABLE test_01457.tf_remote;
SHOW CREATE TABLE test_01457.tf_remote_explicit_structure;
show create table test_1164_memory.r1;
SHOW CREATE TABLE test_alter_decimal;
SHOW CREATE TABLE test_default_delta;
SHOW CREATE TABLE test_optimize_exception;
SHOW CREATE TABLE test_table;
show create table test_view;
SHOW CREATE TABLE test_view_00599;
SHOW CREATE TABLE test_view_filtered;
show create table time_zones format TSVRaw;
show create table tp_2;
show create table ttl;
show create table ttl_00933_1;
SHOW CREATE TABLE tuple FORMAT TSVRaw;
SHOW CREATE TABLE unsigned_types;
show create table user_directories format TSVRaw;
show create table users format TSVRaw;
SHOW CREATE TABLE users_02534;
SHOW CREATE TABLE v1 FORMAT Vertical;
SHOW CREATE TABLE val2;
SHOW CREATE TABLE val;
show create table warnings format TSVRaw;
show create table zeros format TSVRaw;
show create table zeros_mt format TSVRaw;
SHOW CREATE TABLE {CLICKHOUSE_DATABASE:Identifier}.`.inner.wv`;
SHOW CREATE TABLE {CLICKHOUSE_DATABASE:Identifier}.t_mv_00751 FORMAT TabSeparatedRaw;
SHOW CREATE table2;
SHOW CREATE table3;
SHOW CREATE TEMPORARY TABLE t10_02271;
SHOW CREATE TEMPORARY TABLE t1_02271;
SHOW CREATE TEMPORARY TABLE t2_02271;
SHOW CREATE TEMPORARY TABLE t3_02271;
SHOW CREATE TEMPORARY TABLE t4_02271;
SHOW CREATE TEMPORARY TABLE t5_02271;
SHOW CREATE TEMPORARY TABLE t6_02271;
SHOW CREATE TEMPORARY TABLE t7_02271;
SHOW CREATE TEMPORARY TABLE t8_02271;
SHOW CREATE TEMPORARY TABLE t9_02271;
SHOW CREATE TEMPORARY TABLE temp_tab;
SHOW CREATE TEMPORARY TABLE test_01602a;
SHOW CREATE TEMPORARY TABLE test_01602b;
SHOW CREATE TEMPORARY TABLE tmp;
SHOW CREATE TEMPORARY TABLE tmp_log;
SHOW CREATE test;
SHOW CREATE test_1602.DATABASE;
SHOW CREATE test_1602.DICTIONARY;
SHOW CREATE test_1602.TABLE;
SHOW CREATE test_complex_dictionary_10_shards;
SHOW CREATE test_complex_dictionary_load_factor;
SHOW CREATE test_dictionary_10_shards;
SHOW CREATE test_dictionary_10_shards_nullable;
SHOW CREATE test_dictionary_load_factor;
SHOW CREATE test_dictionary_load_factor_nullable;
SHOW CREATE test_sparse_dictionary_load_factor;
SHOW CREATE url;
SHOW CREATE USER `test_user_01075_x@192.168.23.15`;
SHOW CREATE USER `u2_01292@%.myhost.com`;
SHOW CREATE USER `u3_01292@192.168.%.%`;
SHOW CREATE USER `u4_01292@::1`;
SHOW CREATE USER `u5_01292@65:ff0c::/96`;
SHOW CREATE USER sqllt_user FORMAT Null;
SHOW CREATE USER test_user_01073;
SHOW CREATE USER test_user_01075_x;
SHOW CREATE USER u10_01292;
SHOW CREATE USER u16_01292;
SHOW CREATE USER u1_01292, u2_01292, u3_01292, u4_01292, `u5_01292@'%.host.com'`, `u6_01292@'%.host.com'`;
SHOW CREATE USER u1_01292, u2_01292, u3_01292, u4_01292;
SHOW CREATE USER u1_01292;
SHOW CREATE VIEW test_1602.not_exist_view;
SHOW CREATE VIEW test_1602.v;
SHOW CREATE VIEW test_1602.vv;
SHOW CREATE VIEW view;
show create x;
SHOW CURRENT QUOTA;
SHOW DATABASE t_2710_db;
SHOW DATABASES ILIKE '%DE%';
show databases like '%01470';
SHOW DATABASES LIKE '%de%';
SHOW DATABASES LIKE 'sqllt' FORMAT Null;
SHOW DATABASES LIKE '{CLICKHOUSE_DATABASE:String}';
SHOW DATABASES LIMIT 0;
SHOW DATABASES LIMIT 2;
SHOW DATABASES NOT LIKE '%de%';
SHOW DICTIONARIES FROM db LIKE '%reg%' LIMIT 2;
SHOW DICTIONARIES FROM db_01018 LIKE 'dict1';
SHOW DICTIONARIES FROM db_01018;
SHOW DICTIONARIES FROM memory_db LIKE 'dict2';
SHOW DICTIONARIES FROM sqllt FORMAT Null;
SHOW DICTIONARIES FROM test_truncate_database;
SHOW DICTIONARIES FROM {CLICKHOUSE_DATABASE:Identifier};
SHOW EXTENDED COLUMNS FROM tab;
SHOW EXTENDED INDEX FROM tbl;
SHOW FIELDS FROM tab;
SHOW FULL COLUMNS FROM tab;
SHOW GRANTS FOR sqllt_user FORMAT Null;
SHOW GRANTS FOR test_role_01073;
SHOW GRANTS FOR test_user_01073;
SHOW GRANTS FOR test_user_01074;
SHOW GRANTS FOR test_user_01999;
SHOW GRANTS FOR u1_01292;
SHOW GRANTS FORMAT Null;
SHOW INDEX FROM `tbl`;
SHOW INDEX FROM `$4@^7`;
SHOW INDEX FROM `'` FROM `'`;
SHOW INDEX FROM `'`.`'`;
SHOW INDEX FROM database_123456789abcde.tbl;
SHOW INDEX FROM `NULL`;
SHOW INDEX FROM tbl FROM database_123456789abcde;
SHOW INDEX FROM tbl WHERE index_type LIKE '%minmax%';
SHOW INDEX FROM tbl;
SHOW INDEXES FROM tbl;
SHOW INDICES FROM tbl;
SHOW KEYS FROM tbl;
SHOW MERGES LIKE 'your_t%' LIMIT 1;
SHOW MERGES;
SHOW PRIVILEGES;
SHOW QUOTAS;
SHOW SETTING `max_threads`;
SHOW SETTING max_threads;
SHOW SETTINGS ILIKE '%CONNECT_timeout%';
SHOW SETTINGS ILIKE '%CONNECT_timeout%';
SHOW SETTINGS LIKE 'send_timeout';
SHOW TABLE t_2710_show_table;
show tables from db_01517_atomic;
show tables from db_01517_atomic_sync;
show tables from db_01517_ordinary;
SHOW TABLES FROM INFORMATION_SCHEMA;
SHOW TABLES FROM INFORMATION_schema;
SHOW TABLES FROM shard_0;
SHOW TABLES FROM shard_1;
SHOW TABLES FROM sqllt FORMAT Null;
SHOW TABLES FROM system ILIKE '%USER%';
SHOW TABLES FROM system LIKE '%user%';
SHOW TABLES FROM system LIMIT 2;
SHOW TABLES FROM system NOT LIKE '%s%';
SHOW TABLES FROM test_01155_atomic;
SHOW TABLES FROM test_01155_ordinary;
SHOW TABLES FROM test_truncate_database;
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} LIKE 'tes%';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} LIKE 'tes%1';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} LIMIT 2 * 2;
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} LIMIT 2;
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} NOT LIKE 'tes%';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} NOT LIKE 'tes%2';
SHOW TABLES from {CLICKHOUSE_DATABASE:Identifier};
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier};
show tables from {CLICKHOUSE_DATABASE:Identifier};
SHOW tables FROM {CLICKHOUSE_DATABASE:Identifier};
SHOW TABLES ILIKE 'tES%';
SHOW TABLES in system where engine like '%System%';
SHOW TABLES LIKE 'tes%';
SHOW TABLES LIKE 'tes%1';
SHOW TABLES NOT ILIKE '%';
SHOW TABLES NOT ILIKE 'TeS%';
SHOW TABLES NOT LIKE '%';
SHOW TABLES NOT LIKE 'tes%';
SHOW TABLES NOT LIKE 'tes%2';
SHOW TABLES;
show tables;
SHOW TEMPORARY TABLES LIKE 'temp_tab';
SHOW USERS;