ALTER TABLE table1
	ADD COLUMN col2 integer;

ALTER TABLE ONLY table1
	ALTER COLUMN col2 SET NOT NULL;

ALTER TABLE table1
	ADD COLUMN col3 integer;

ALTER TABLE ONLY table1
	ALTER COLUMN col3 SET DEFAULT 5;

ALTER TABLE ONLY table1
	ALTER COLUMN col3 SET NOT NULL;
