ALTER TABLE  testtable
	ALTER COLUMN field1 SET STORAGE EXTENDED;

ALTER TABLE  testtable
	ALTER COLUMN field2 SET STORAGE EXTENDED;

ALTER TABLE  testtable
	ALTER COLUMN field3 SET STORAGE MAIN;

ALTER TABLE  testtable
	ALTER COLUMN field4 SET STORAGE MAIN;
