CREATE TABLE t2 (
	c1 integer,
	c2 text
);

ALTER TABLE t2 OWNER TO botov_av;

-- TABLE t2 GRANT

GRANT SELECT ON TABLE t2 TO levsha_aa;

-- COLUMN c1 GRANT

GRANT INSERT(c1), REFERENCES(c1), UPDATE(c1) ON TABLE t2 TO levsha_aa;

GRANT SELECT ON TABLE t1 TO levsha_aa;

ALTER TABLE t1
	ADD COLUMN c2 text;

-- COLUMN c2 GRANT

GRANT ALL(c2) ON TABLE t1 TO maindb;

-- COLUMN c1 GRANT

REVOKE ALL(c1) ON TABLE t1 FROM PUBLIC;
REVOKE ALL(c1) ON TABLE t1 FROM botov_av;
GRANT ALL(c1) ON TABLE t1 TO maindb;
GRANT INSERT(c1), REFERENCES(c1), UPDATE(c1) ON TABLE t1 TO levsha_aa;

CREATE VIEW v1 AS
	SELECT t1.c1
   FROM t1;

-- VIEW v1 GRANT

REVOKE ALL(c1) ON TABLE v1 FROM PUBLIC;
REVOKE ALL(c1) ON TABLE v1 FROM levsha_aa;
GRANT UPDATE(c1) ON TABLE v1 TO maindb;
