SET search_path = public, pg_catalog;

ALTER TABLE testtable
	DROP CONSTRAINT testtable_pkey;

ALTER TABLE ONLY testtable
	ALTER COLUMN field1 DROP NOT NULL;

ALTER TABLE ONLY testtable
	ALTER COLUMN field3 DROP DEFAULT;

ALTER TABLE ONLY testtable
	ALTER COLUMN field2 SET DEFAULT 5000;

ALTER TABLE ONLY testtable
	ALTER COLUMN field4 DROP DEFAULT;

ALTER TABLE ONLY testtable
	ALTER COLUMN field4 SET NOT NULL;
