ALTER TABLE testtable
	DROP CONSTRAINT testtable_pkey;

ALTER TABLE testtable
	ALTER COLUMN field2 SET DEFAULT 5000, 
	ALTER COLUMN field4 DROP DEFAULT, 
	ALTER COLUMN field4 SET NOT NULL, 
	ALTER COLUMN field1 DROP NOT NULL, 
	ALTER COLUMN field3 DROP DEFAULT;
