SELECT proname,
        proowner,
        (SELECT lanname
         FROM pg_catalog.pg_language l
         WHERE l.oid = prolang) lang_name,
        prosrc,
        proiswindow,
        provolatile,
        proleakproof,
        proisstrict,
        prosecdef,
        procost::real,
        prorows::real,
        proconfig,
        probin,
        prorettype::bigint,
        proallargtypes::bigint[],
        proargmodes,
        proargnames,
        pg_get_function_arguments(p.oid) AS proarguments,
        pg_get_function_identity_arguments(p.oid) AS proarguments_without_default,
        proargdefaults,
        proacl AS aclArray,
        d.description AS comment,
        proretset,
        array_agg(dep.deptype) AS deps
FROM pg_catalog.pg_proc p
LEFT JOIN pg_catalog.pg_description d ON d.objoid = p.oid
LEFT JOIN pg_catalog.pg_depend dep ON p.oid = dep.objid
WHERE pronamespace = ?
    AND proisagg = FALSE
GROUP BY p.oid,
         proname,
         proowner,
         lang_name,
         prosrc,
         proiswindow,
         provolatile,
         proleakproof,
         proisstrict,
         prosecdef,
         procost,
         prorows,
         proconfig,
         probin,
         prorettype,
         proowner,
         proallargtypes,
         proargmodes,
         proargnames,
         proarguments,
         proargdefaults,
         comment,
         aclArray,
         proretset