SET search_path = pg_catalog;

CREATE TABLE public.sales2 (
	id integer ENCODING (COMPRESSTYPE = none, COMPRESSLEVEL = 0, BLOCKSIZE = 32768),
	year integer ENCODING (COMPRESSTYPE = none, COMPRESSLEVEL = 0, BLOCKSIZE = 32768),
	qtr integer ENCODING (COMPRESSTYPE = none, COMPRESSLEVEL = 0, BLOCKSIZE = 32768),
	c_rank integer ENCODING (COMPRESSTYPE = none, COMPRESSLEVEL = 0, BLOCKSIZE = 32768),
	code character(1) ENCODING (COMPRESSTYPE = none, COMPRESSLEVEL = 0, BLOCKSIZE = 32768),
	region text ENCODING (COMPRESSTYPE = none, COMPRESSLEVEL = 0, BLOCKSIZE = 32768)
)
PARTITION BY LIST (code)
USING ao_column
DISTRIBUTED BY (id);