CREATE CLUSTERED INDEX [index_c2] ON [dbo].[table1] ([c2])
WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 240 MINUTES)
GO

CREATE CLUSTERED INDEX [idx_1] ON [dbo].[table1] ([c1])
WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 5 MINUTES, ABORT_AFTER_WAIT = BLOCKERS)))
GO