CREATE USER [test_user] FOR LOGIN [test_user] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [test_user2] FOR LOGIN [test_user2]
GO

CREATE USER [test_user3] FOR LOGIN [test_user3] WITH DEFAULT_SCHEMA=[test]
GO

CREATE USER [test_user4] WITH DEFAULT_SCHEMA=[dbo],
DEFAULT_LANGUAGE=French,
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=ON;
GO

CREATE USER [test_user5] WITH DEFAULT_SCHEMA=[test],
DEFAULT_LANGUAGE=French,
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=ON;
GO

CREATE USER [test_user6] WITH PASSWORD='p@$$w0rD';
GO
