ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c3] ADD ROWGUIDCOL
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c4] ADD PERSISTED
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c5] ADD SPARSE
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c6] ADD MASKED WITH (FUNCTION = 'partial(1, "XXX''XXXX", 0)')
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c7] ADD MASKED WITH (FUNCTION = 'default()')
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c8] ADD NOT FOR REPLICATION
GO
