BEGIN TRANSACTION
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[table2](
	[c1] [int] NOT NULL,
	[c2] [varchar](100) NULL
)
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[table3](
	[c1] [int] NOT NULL,
	[c2] [varchar](100) NULL
)
GO

ALTER TABLE [dbo].[table1] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON)
GO

ALTER TABLE [dbo].[table2]
	ADD CONSTRAINT [PK_table2] PRIMARY KEY CLUSTERED  ([c1]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[table3]
	ADD CONSTRAINT [PK_table3] PRIMARY KEY CLUSTERED  ([c1])
GO

ALTER TABLE [dbo].[table2] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON)
GO

ALTER TABLE [dbo].[table3] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON)
GO

COMMIT
GO