SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[table1](
    [c1] [int] NOT NULL,
    [c2] [int] NOT NULL,
    [c3] [varchar](100) NOT NULL)
GO

CREATE CLUSTERED INDEX [index_c2] ON [dbo].[table1] ([c2]) WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 240 MINUTES)
GO

CREATE CLUSTERED INDEX [idx_1] ON [dbo].[table1] ([c1]) WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 5 MINUTES, ABORT_AFTER_WAIT = BLOCKERS)));
GO

-- test CLUSTERED columnstore index
CREATE TABLE [dbo].[table0](
	[col1] [int] NULL
) ON [PRIMARY]
WITH (DATA_COMPRESSION = COLUMNSTORE)
GO

CREATE CLUSTERED COLUMNSTORE INDEX [idx_table0] ON [dbo].[table0]
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
GO

-- test nonclusterd columnstore index
CREATE TABLE [dbo].[table3](
	[col1] [int] NULL,
	[col2] [int] NULL,
	[col3] [int] NULL
) ON [PRIMARY]
GO

CREATE NONCLUSTERED COLUMNSTORE INDEX [idx_table3] ON [dbo].[table3]
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
GO

--add table with COLUMNSTORE index with ORDER columns in table(MSSQL 2022)
CREATE TABLE [dbo].[table6](
	[col1] [int] NULL,
	[col2] [int] NULL,
	[col3] [int] NULL
) ON [PRIMARY]
WITH (DATA_COMPRESSION = COLUMNSTORE)
GO

CREATE NONCLUSTERED COLUMNSTORE INDEX [idx_table6] ON [dbo].[table6] ([col2], [col1]) ORDER (col3, col1)
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
ON [PRIMARY]
GO

-- add table with CLUSTERED COLUMNSTORE ORDER index
CREATE TABLE dbo.t4
(
    [c1] [int] NOT NULL,
    [c2] [int] NOT NULL,
    [c3] [varchar](100) NOT NULL,
    INDEX ix_4 CLUSTERED COLUMNSTORE  ORDER ([c2], [c1])
);
GO