ALTER TABLE [dbo].[t2]
	DROP CONSTRAINT [UK_t2]
GO

ALTER TABLE [dbo].[t2]
	DROP COLUMN [col1]
GO

ALTER TABLE [dbo].[t3] SET (SYSTEM_VERSIONING = OFF)
GO

ALTER TABLE [dbo].[t3] SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[TemporalHistoryFor_t3], HISTORY_RETENTION_PERIOD = 3 WEEK))
GO

ALTER TABLE [dbo].[t4] SET (SYSTEM_VERSIONING = OFF)
GO

ALTER TABLE [dbo].[t4] SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[TemporalHistoryFor_t4]))
GO

ALTER TABLE [dbo].[t1]
	ADD [col1] [int]
GO

ALTER TABLE [dbo].[t1]
	ADD CONSTRAINT [UK_t1] UNIQUE NONCLUSTERED  ([col1]) ON [PRIMARY]
GO