ALTER TABLE [dbo].[Department] SET (SYSTEM_VERSIONING = OFF)
GO

ALTER TABLE [dbo].[Department]
	DROP CONSTRAINT [PK__Departme__718447F87C145BBF]
GO

ALTER TABLE [dbo].[Department]
	ADD CONSTRAINT [PK__Departme__718447F87C145BBF] PRIMARY KEY CLUSTERED  ([DepartmentName]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Department] SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[MSSQL_TemporalHistoryFor_Department], HISTORY_RETENTION_PERIOD = 3 WEEK))
GO
