ALTER TABLE default.t2_1
	DROP CONSTRAINT ch3;

ALTER TABLE default.t2_1
	DROP INDEX ind2;

ALTER TABLE default.t2_1
	DROP INDEX ind3;

ALTER TABLE default.t1_1
	DROP PROJECTION IF EXISTS proj1;

ALTER TABLE default.t1_1
	ADD PROJECTION proj1 (SELECT col1, col2 ORDER BY col2);

ALTER TABLE default.t1_1
	ADD PROJECTION proj2 (SELECT * ORDER BY col2);

ALTER TABLE default.t1_2
	DROP PROJECTION IF EXISTS proj2;

ALTER TABLE default.t1_2
	DROP PROJECTION IF EXISTS proj1;

ALTER TABLE default.t1_2
	ADD PROJECTION proj1 (SELECT * ORDER BY col2);

ALTER TABLE default.t2_2 ADD INDEX ind3 col1 > col2 TYPE bloom_filter;

ALTER TABLE default.t2_2 ADD INDEX ind4 col1 > 0 TYPE bloom_filter;

ALTER TABLE default.t2_1
	DROP INDEX ind1;

ALTER TABLE default.t2_2 ADD CONSTRAINT ch3 CHECK col2 > 0;

ALTER TABLE default.t2_1
	DROP CONSTRAINT ch1;

ALTER TABLE default.t2_2
	DROP CONSTRAINT ch2;

ALTER TABLE default.t2_1 ADD INDEX ind1 col1 > 0 TYPE bloom_filter;

ALTER TABLE default.t2_1 ADD CONSTRAINT ch1 CHECK col1 > 10;

ALTER TABLE default.t2_2 ADD CONSTRAINT ch2 CHECK col1 > col2;
