ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col2_2] DROP ROWGUIDCOL
GO

-- DEPCY: This CONSTRAINT UQ_1_1 depends on the COLUMN: [dbo].[t1].[col1_1]

ALTER TABLE [dbo].[t1]
	DROP CONSTRAINT [UQ_1_1]
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col1_1] [bigint] NOT NULL
GO

-- DEPCY: This CONSTRAINT UQ_1_2 depends on the COLUMN: [dbo].[t1].[col1_2]

ALTER TABLE [dbo].[t1]
	DROP CONSTRAINT [UQ_1_2]
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col1_2] [bigInt] NULL
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col2_1] ADD ROWGUIDCOL
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col3_1] ADD NOT FOR REPLICATION
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col3_2] DROP NOT FOR REPLICATION
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col4_1] ADD SPARSE
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [col4_2] DROP SPARSE
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [c_1] ADD PERSISTED
GO

-- DEPCY: This CONSTRAINT UQ_3_2 depends on the COLUMN: [dbo].[t1].[c_2]

ALTER TABLE [dbo].[t1]
	DROP CONSTRAINT [UQ_3_2]
GO

ALTER TABLE [dbo].[t1]
	ALTER COLUMN [c_2] DROP PERSISTED
GO

ALTER TABLE [dbo].[t1]
	ADD CONSTRAINT [UQ_1_1] UNIQUE NONCLUSTERED  ([col1_1]) ON [test1fg]
GO

ALTER TABLE [dbo].[t1]
	ADD CONSTRAINT [UQ_1_2] UNIQUE NONCLUSTERED  ([col1_2]) ON [test1fg]
GO

ALTER TABLE [dbo].[t1]
	ADD CONSTRAINT [UQ_3_2] UNIQUE NONCLUSTERED  ([c_2]) ON [test1fg]
GO
