ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c3] DROP ROWGUIDCOL
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c4] DROP PERSISTED
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c5] DROP SPARSE
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c6] DROP MASKED
GO

ALTER TABLE [dbo].[table1]
	ALTER COLUMN [c7] DROP NOT FOR REPLICATION
GO
