-- DEPCY: This INDEX ix_1 depends on the TABLE: [dbo].[t1]

DROP INDEX [ix_1] ON [dbo].[t1]
GO

DROP TABLE [dbo].[t1]
GO

-- DEPCY: This INDEX ix_3 depends on the TABLE: [dbo].[t3]

DROP INDEX [ix_3] ON [dbo].[t3]
GO

DROP TABLE [dbo].[t3]
GO

-- DEPCY: This INDEX ix_4 depends on the TABLE: [dbo].[t4]

DROP INDEX [ix_4] ON [dbo].[t4]
GO

DROP TABLE [dbo].[t4]
GO

CREATE UNIQUE NONCLUSTERED INDEX [index_table1] ON [dbo].[table1] ([c1], [c2] DESC)
WITH (DROP_EXISTING = ON)
GO

CREATE NONCLUSTERED COLUMNSTORE INDEX [idx_table0] ON [dbo].[table0] ([c1], [c2])
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE, DROP_EXISTING = ON)
ON [PRIMARY]
GO

CREATE CLUSTERED COLUMNSTORE INDEX [idx_table2] ON [dbo].[table2]
WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE, DROP_EXISTING = ON)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [idx_table3] ON [dbo].[table3] ([c1], [c3])
WITH (DROP_EXISTING = ON)
ON [PRIMARY]
GO

CREATE CLUSTERED COLUMNSTORE INDEX [idx_table6] ON [dbo].[table6]
ORDER ([col3], [col1])
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE, DROP_EXISTING = ON)
ON [PRIMARY]
GO

CREATE CLUSTERED COLUMNSTORE INDEX [ix_2] ON [dbo].[t2]
ORDER ([c2], [c1])
WITH (DROP_EXISTING = ON)
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[t1](
	[c1] [int] NULL
) ON [PRIMARY]
GO

CREATE NONCLUSTERED COLUMNSTORE INDEX [ix_1] ON [dbo].[t1] ([c1])
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[t3](
	[c1] [int] NOT NULL,
	[c2] [int] NOT NULL,
	[c3] [varchar](100) NOT NULL
) ON [PRIMARY]
WITH (DATA_COMPRESSION = COLUMNSTORE)
GO

CREATE NONCLUSTERED COLUMNSTORE INDEX [ix_3] ON [dbo].[t3] ([c3], [c1])
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[t4](
	[c1] [int] NOT NULL,
	[c2] [int] NOT NULL,
	[c3] [varchar](100) NOT NULL
)
GO

CREATE CLUSTERED COLUMNSTORE INDEX [ix_4] ON [dbo].[t4]
ORDER ([c2], [c1])
GO