CREATE NONCLUSTERED INDEX [index_table1] ON [dbo].[table1] ([c1])
WITH (PAD_INDEX = OFF, FILLFACTOR = 70, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, STATISTICS_INCREMENTAL = OFF, DROP_EXISTING = ON, ONLINE = OFF, RESUMABLE = OFF, MAX_DURATION = 4, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, MAXDOP = 30, DATA_COMPRESSION = ROW, XML_COMPRESSION = OFF)
ON [PRIMARY]
GO
