SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[table1](
    [c1] [int] NOT NULL,
    [c2] [int] NOT NULL,
    [c3] [varchar](100) NOT NULL)
ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [index_table1] ON [dbo].[table1] ([c1])
WITH (
 PAD_INDEX = OFF,
 FILLFACTOR = 70,
 SORT_IN_TEMPDB = OFF,
 IGNORE_DUP_KEY = OFF,
 STATISTICS_NORECOMPUTE = OFF,
 STATISTICS_INCREMENTAL = OFF,
 DROP_EXISTING = OFF,
 ONLINE = OFF,
 RESUMABLE = OFF,
 MAX_DURATION = 4,
 ALLOW_ROW_LOCKS = OFF,
 ALLOW_PAGE_LOCKS = OFF,
 OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF,
 MAXDOP = 30,
 DATA_COMPRESSION = ROW,
 XML_COMPRESSION = OFF)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [index_table2] ON [dbo].[table1] ([c2])
WITH (
 PAD_INDEX = OFF,
 IGNORE_DUP_KEY = OFF,
 STATISTICS_INCREMENTAL = OFF)
ON [PRIMARY]
GO