SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TABLE [dbo].[table1](
    [c1] [int] NOT NULL,
    [c2] [int] NOT NULL,
    [c3] [varchar](100) NOT NULL)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [index_table1] ON [dbo].[table1] ([c1])
WITH (
 PAD_INDEX = ON,
 FILLFACTOR = 50,
 SORT_IN_TEMPDB = ON,
 IGNORE_DUP_KEY = ON,
 STATISTICS_NORECOMPUTE = ON,
 STATISTICS_INCREMENTAL = ON,
 DROP_EXISTING = ON,
 ONLINE = ON,
 RESUMABLE = ON,
 MAX_DURATION = 5,
 ALLOW_ROW_LOCKS = ON,
 ALLOW_PAGE_LOCKS = ON,
 OPTIMIZE_FOR_SEQUENTIAL_KEY = ON,
 MAXDOP = 20,
 DATA_COMPRESSION = NONE,
 XML_COMPRESSION = ON)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [index_table2] ON [dbo].[table1] ([c2])
WITH (
 STATISTICS_INCREMENTAL = OFF,
 IGNORE_DUP_KEY = OFF,
 PAD_INDEX = OFF)
ON [PRIMARY]
GO