CREATE SCHEMA [test]
GO

CREATE USER [test_user] FOR LOGIN [test_user] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [test_user1] FOR LOGIN [test_user1] 
WITH DEFAULT_SCHEMA=[test],
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=OFF;
GO

CREATE USER [test_user2] WITH PASSWORD='p@$$w0rD',
DEFAULT_SCHEMA=[dbo],
DEFAULT_LANGUAGE=French;
GO

CREATE USER [test_user3] WITH PASSWORD='p@$$w0rD',
DEFAULT_SCHEMA=[test],
DEFAULT_LANGUAGE=French,
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=ON;
GO

CREATE USER [test_user4] WITH PASSWORD='p@$$w0rD'
GO

CREATE USER [test_user5] FOR LOGIN [test_user5] 
WITH DEFAULT_SCHEMA=[test],
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=ON;
GO

CREATE USER [test_user6] WITH PASSWORD='p@$$w0rD',
DEFAULT_SCHEMA=[test],
DEFAULT_LANGUAGE=French,
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=ON;
GO

CREATE USER [test_user7] WITH PASSWORD='p@$$w0rD',
DEFAULT_SCHEMA=[dbo],
DEFAULT_LANGUAGE=NONE,
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=OFF;
GO

CREATE USER [test_user8] WITH PASSWORD='p@$$w0rD',
DEFAULT_SCHEMA=[test],
DEFAULT_LANGUAGE=English,
ALLOW_ENCRYPTED_VALUE_MODIFICATIONS=OFF;
GO
