CREATE EVENT TRIGGER evt1
ON ddl_command_end
WHEN TAG IN ('ALTER COLLATION')
EXECUTE PROCEDURE proc1();

ALTER EVENT TRIGGER evt1 OWNER TO role1;
ALTER EVENT TRIGGER evt1 DISABLE;

CREATE EVENT TRIGGER evt2
ON ddl_command_start
EXECUTE PROCEDURE proc2();

ALTER EVENT TRIGGER evt2 ENABLE REPLICA;

CREATE EVENT TRIGGER evt3
ON ddl_command_start
EXECUTE PROCEDURE proc3();

ALTER EVENT TRIGGER evt3 ENABLE ALWAYS;