SET search_path = pg_catalog;

ALTER TABLE public.testtable RENAME TO testtable_randomly_generated_part;

ALTER TABLE public.testtable1 RENAME TO testtable1_randomly_generated_part;

ALTER TABLE public.testtable2 RENAME TO testtable2_randomly_generated_part;

ALTER SEQUENCE public.testtable2_id_seq RENAME TO testtable2_id_seq_randomly_generated_part;

CREATE TABLE public.testtable (
	id bigint NOT NULL,
	c2 text NOT NULL,
	c4 bigint,
	c3 bigint
);

INSERT INTO public.testtable(id, c2, c3)
SELECT id, c2, c3 FROM public.testtable_randomly_generated_part;

DROP TABLE public.testtable_randomly_generated_part;

CREATE TABLE public.testtable1 (
	id bigint NOT NULL,
	c2 text NOT NULL,
	c4 text NOT NULL,
	c3 bigint
);

ALTER TABLE public.testtable1 ALTER COLUMN c4 ADD GENERATED ALWAYS AS IDENTITY (
	SEQUENCE NAME public.testtable1_c4_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

INSERT INTO public.testtable1(id, c2, c3)
SELECT id, c2, c3 FROM public.testtable1_randomly_generated_part;

DROP TABLE public.testtable1_randomly_generated_part;

CREATE TABLE public.testtable2 (
	id bigint NOT NULL,
	c2 text NOT NULL,
	c4 text NOT NULL,
	c3 bigint
);

ALTER TABLE public.testtable2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME public.testtable2_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

ALTER TABLE public.testtable2 OWNER TO khazieva_gr;

INSERT INTO public.testtable2(id, c2, c3)
OVERRIDING SYSTEM VALUE
SELECT id, c2, c3 FROM public.testtable2_randomly_generated_part;

DO LANGUAGE plpgsql $_$
DECLARE restart_var bigint = (SELECT COALESCE(
    (SELECT nextval(pg_get_serial_sequence('public.testtable2_randomly_generated_part', 'id'))),
    (SELECT MAX(id) + 1 FROM public.testtable2),
    1));
BEGIN
    EXECUTE $$ ALTER TABLE public.testtable2 ALTER COLUMN id RESTART WITH $$ || restart_var || ';' ;
END
$_$;

DROP TABLE public.testtable2_randomly_generated_part;