
CREATE TABLE public.measurement (
    id bigint,
    city_id integer NOT NULL,
    country_id integer,
    logdate integer
)
PARTITION BY RANGE (logdate); 

ALTER TABLE public.measurement OWNER TO khazieva_gr;

ALTER TABLE public.measurement ALTER COLUMN city_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.measurement_city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1
);

ALTER TABLE public.measurement ALTER COLUMN country_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurement_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1
);

CREATE TABLE public.measurement_1 PARTITION OF public.measurement
FOR VALUES FROM (1) TO (4);

ALTER TABLE public.measurement_1 OWNER TO khazieva_gr; 

CREATE TABLE public.measurement_2 PARTITION OF public.measurement
FOR VALUES FROM (6) TO (10)
PARTITION BY RANGE (logdate);

ALTER TABLE public.measurement_2 OWNER TO khazieva_gr;

CREATE TABLE public.measurement_3 PARTITION OF public.measurement_2
FOR VALUES FROM (7) TO (9);

ALTER TABLE public.measurement_3 OWNER TO khazieva_gr;
--------------------------------------------------------------------------------