SET search_path = pg_catalog;

-- DEPCY: This VIEW v depends on the TABLE: public.tbl

DROP VIEW public.v;

-- DEPCY: This TRIGGER events_insert depends on the TABLE: public.tbl

DROP TRIGGER events_insert ON public.tbl;

-- DEPCY: This FUNCTION events_insert_trigger depends on the TABLE: public.tbl

DROP FUNCTION public.events_insert_trigger();

-- DEPCY: This CONSTRAINT tbl_name22_check depends on the TABLE: public.tbl

ALTER TABLE public.tbl
	DROP CONSTRAINT tbl_name22_check;

-- DEPCY: This CONSTRAINT tbl_pkey depends on the TABLE: public.tbl

ALTER TABLE public.tbl
	DROP CONSTRAINT tbl_pkey;

ALTER TABLE public.tbl RENAME TO tbl_randomly_generated_part;

ALTER SEQUENCE public.tbl_did_seq RENAME TO tbl_did_seq_randomly_generated_part;

ALTER SEQUENCE public.tbl_did_2_seq RENAME TO tbl_did_2_seq_randomly_generated_part;

CREATE TABLE public.tbl (
	did integer NOT NULL,
	did_2 integer NOT NULL,
	name22 character varying(40) NOT NULL,
	event_time timestamp without time zone DEFAULT now() NOT NULL,
	description integer DEFAULT 55777,
	calculated bigint GENERATED ALWAYS AS ((did + 2000)) STORED
);

ALTER TABLE public.tbl ALTER COLUMN did ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME public.tbl_did_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

ALTER TABLE public.tbl ALTER COLUMN did_2 ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME public.tbl_did_2_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

INSERT INTO public.tbl(did, did_2, name22, event_time, description)
OVERRIDING SYSTEM VALUE
SELECT did, did_2, name22, event_time, description FROM public.tbl_randomly_generated_part;

DO LANGUAGE plpgsql $_$
DECLARE restart_var bigint = (SELECT COALESCE(
    (SELECT nextval(pg_get_serial_sequence('public.tbl_randomly_generated_part', 'did'))),
    (SELECT MAX(did) + 1 FROM public.tbl),
    1));
BEGIN
    EXECUTE $$ ALTER TABLE public.tbl ALTER COLUMN did RESTART WITH $$ || restart_var || ';' ;
END
$_$;

DO LANGUAGE plpgsql $_$
DECLARE restart_var bigint = (SELECT COALESCE(
    (SELECT nextval(pg_get_serial_sequence('public.tbl_randomly_generated_part', 'did_2'))),
    (SELECT MAX(did_2) + 1 FROM public.tbl),
    1));
BEGIN
    EXECUTE $$ ALTER TABLE public.tbl ALTER COLUMN did_2 RESTART WITH $$ || restart_var || ';' ;
END
$_$;

DROP TABLE public.tbl_randomly_generated_part;

CREATE VIEW public.v AS
	SELECT tbl.name22,
    tbl.description,
    1 AS qwerty
   FROM public.tbl;

CREATE OR REPLACE FUNCTION public.events_insert_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  UPDATE public.tbl
  SET description = (SELECT trunc(random() * 100 + 1)) 
  WHERE did_2 = 2;
  RETURN NULL;
END;
$$;

CREATE TRIGGER events_insert
	AFTER INSERT ON public.tbl
	FOR EACH ROW
	EXECUTE PROCEDURE public.events_insert_trigger();

ALTER TABLE public.tbl
	ADD CONSTRAINT tbl_name22_check CHECK (((name22)::text <> ''::text));

ALTER TABLE public.tbl
	ADD CONSTRAINT tbl_pkey PRIMARY KEY (did);