--drop identitiy column
CREATE TABLE public.testtable (
    id bigint NOT NULL,
    c2 text NOT NULL,
    c4 bigint, --added
    c3 bigint
);

--------------------------------------------------------------------------------
-- change identitiy column
CREATE TABLE public.testtable1 (
    id bigint NOT NULL,
    c2 text NOT NULL,
    c4 text NOT NULL, --added
    c3 bigint
);

ALTER TABLE public.testtable1 ALTER COLUMN c4 ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.testtable1_c4_seq
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1
);

--------------------------------------------------------------------------------
--change identitiy type
CREATE TABLE public.testtable2 (
    id bigint NOT NULL,
    c2 text NOT NULL,
    c4 text NOT NULL, --added
    c3 bigint
);

ALTER TABLE public.testtable2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.testtable2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1
);

ALTER TABLE public.testtable2 OWNER TO khazieva_gr;