CREATE TABLE t1 (
	c1 integer
);

ALTER TABLE t1 OWNER TO botov_av;

-- TABLE t1 GRANT

GRANT ALL ON TABLE public.t1 TO PUBLIC;

-- COLUMN c1 GRANT

REVOKE ALL(c1) ON TABLE t1 FROM PUBLIC;
REVOKE ALL(c1) ON TABLE t1 FROM botov_av;
GRANT ALL(c1) ON TABLE t1 TO maindb;
