
CREATE TABLE t1 (
    c1 integer
);


CREATE SEQUENCE s1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE s1 OWNED BY t1.c1;


ALTER TABLE ONLY t1 ALTER COLUMN c1 SET DEFAULT nextval('s1'::regclass);