create domain domaindroptest int4;
comment on domain domaindroptest is 'About to drop this..';
create domain dependenttypetest domaindroptest;
drop domain domaindroptest;
create domain domainvarchar varchar(5);
create domain domainnumeric numeric(8,2);
create domain domainint4 int4;
create domain domaintext text;
drop domain domainint4 restrict;
drop domain domaintext;
create domain domainint4arr int4[1];
create domain domainchar4arr varchar(4)[2][3];
drop domain domainint4arr restrict;
drop domain domainchar4arr restrict;
create domain dia as int[];
drop domain dia;
create domain dcomptype as comptype;
alter domain dcomptype add constraint c1 check ((value).r <= (value).i);
alter domain dcomptype add constraint c2 check ((value).r > (value).i);  -- fail
create domain dcomptype as comptype;
alter domain dcomptype add constraint c1 check ((value).r > 0);
comment on constraint c1 on domain dcomptype is 'random commentary';
create domain dcomptypea as comptype[];
--alter domain dcomptypea add constraint c1 check (value[1].r <= value[1].i);
--alter domain dcomptypea add constraint c2 check (value[1].r > value[1].i);  -- fail
create domain posint as int check (value > 0);
create domain vc4 as varchar(4);
create domain dposinta as posint[];
create domain dnotnull varchar(15) NOT NULL;
create domain dnull    varchar(15);
create domain dcheck   varchar(15) NOT NULL CHECK (VALUE = 'a' OR VALUE = 'c' OR VALUE = 'd');
create domain ddef1 int4 DEFAULT 3;
create domain ddef2 oid DEFAULT '12';
create domain ddef3 text DEFAULT 5;
create domain ddef4 int4 DEFAULT nextval('ddef4_seq');
create domain ddef5 numeric(8,2) NOT NULL DEFAULT '12.12';
create domain dnotnulltest integer;
alter domain dnotnulltest set not null;
alter domain dnotnulltest drop not null;
alter domain ddef1 set default '42';
alter domain ddef1 drop default;
create domain con as integer;
alter domain con add constraint t check (VALUE < 1);
alter domain con add constraint t check (VALUE < 34);
alter domain con add check (VALUE > 0);
alter domain con drop constraint t;
alter domain con drop constraint nonexistent;
alter domain con drop constraint if exists nonexistent;
create domain things AS INT;
ALTER DOMAIN things ADD CONSTRAINT meow CHECK (VALUE < 11);
ALTER DOMAIN things ADD CONSTRAINT meow CHECK (VALUE < 11) NOT VALID;
ALTER DOMAIN things VALIDATE CONSTRAINT meow;
create domain dom as integer;
alter domain dom set not null;
alter domain dom drop not null;
alter domain dom add constraint domchkgt6 check(value > 6);
alter domain dom drop constraint domchkgt6 restrict;
create domain vchar4 varchar(4);
create domain dinter vchar4 check (substring(VALUE, 1, 1) = 'x');
create domain dtop dinter check (substring(VALUE, 2, 1) = '1');
create domain str_domain as text not null;
create domain str_domain2 as text check (value <> 'foo') default 'foo';
create domain pos_int as int4 check (value > 0) not null;
create domain posint as int4;
alter domain posint add constraint c1 check(value >= 0);
create domain ddtest1d as ddtest1;
create domain ddtest1d as ddtest1[]; 
create domain posint2 as posint check (value % 2 = 0);
alter domain posint add constraint c2 check(value >= 10); -- fail 
alter domain posint add constraint c2 check(value > 0); -- OK
drop domain posint cascade;
create domain mynums as numeric(4,2)[1];
create domain mynums2 as mynums;
create domain orderedpair as int[2] check (value[1] < value[2]);
create domain inotnull int check (sql_is_distinct_from(value, null));
create domain testdomain1 as int constraint unsigned check (value > 0);
alter domain testdomain1 rename constraint unsigned to unsigned_foo;
alter domain testdomain1 drop constraint unsigned_foo;
drop domain testdomain1;
CREATE DOMAIN js_int_not_null  AS int     NOT NULL;
CREATE DOMAIN js_int_array_1d  AS int[]   CHECK(array_length(VALUE, 1) = 3);
CREATE DOMAIN js_int_array_2d  AS int[][] CHECK(array_length(VALUE, 2) = 3);
create domain j_ordered_pair as j_unordered_pair check((value).x <= (value).y);
CREATE DOMAIN testboolxmldomain AS bool;
CREATE DOMAIN testdatexmldomain AS date;
CREATE DOMAIN testxmldomain AS varchar;