SET search_path = pg_catalog;

CREATE TABLE public.temp_test (
	id integer NOT NULL,
	column1 integer
);

DO $$
BEGIN
	ALTER TABLE public.temp_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
		SEQUENCE NAME public.temp_test_id_seq
		START WITH 1
		INCREMENT BY 1
		NO MAXVALUE
		NO MINVALUE
		CACHE 1
	);
EXCEPTION WHEN OTHERS THEN
	IF (SQLSTATE = '42P07') THEN
		RAISE NOTICE '%, skip', SQLERRM;
	ELSE
		RAISE;
	END IF;
END; $$
LANGUAGE 'plpgsql';

CREATE TABLE public.temp_test_1 (
	id integer,
	column1 integer
);

DO $$
BEGIN
	ALTER TABLE public.temp_test
		ADD CONSTRAINT temp_test_pkey PRIMARY KEY (id);
EXCEPTION WHEN OTHERS THEN
	IF (SQLSTATE = '42P16') THEN
		RAISE NOTICE '%, skip', SQLERRM;
	ELSE
		RAISE;
	END IF;
END; $$
LANGUAGE 'plpgsql';

DO $$
BEGIN
	ALTER TABLE public.temp_test
		ADD CONSTRAINT fk_test FOREIGN KEY (column1) REFERENCES public.temp_test_fk(id) DEFERRABLE;
EXCEPTION WHEN OTHERS THEN
	IF (SQLSTATE = '42710') THEN
		RAISE NOTICE '%, skip', SQLERRM;
	ELSE
		RAISE;
	END IF;
END; $$
LANGUAGE 'plpgsql';
