CREATE TABLE public.temp_test (
    id integer NOT NULL,
    column1 int
);

CREATE TABLE public.temp_test_1 (
    id integer,
    column1 int
);

--add sequence to column
ALTER TABLE public.temp_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.temp_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1
);

ALTER TABLE public.temp_test
    ADD CONSTRAINT temp_test_pkey PRIMARY KEY (id);

ALTER TABLE public.temp_test
    ADD CONSTRAINT fk_test FOREIGN KEY (column1) REFERENCES public.temp_test_fk(id) DEFERRABLE;