package ru.taximaxim.codekeeper.ui;

public class PgCodekeeperUIException extends Exception {

    /**
     * Autogenerated serial id by Eclipse
     */
    private static final long serialVersionUID = -1230666490485802474L;

    public PgCodekeeperUIException() {
        // TODO Auto-generated constructor stub
    }

    public PgCodekeeperUIException(String message) {
        super(message);
    }

    public PgCodekeeperUIException(Throwable cause) {
        super(cause);
    }

    public PgCodekeeperUIException(String message, Throwable cause) {
        super(message, cause);
    }

    public PgCodekeeperUIException(String message, Throwable cause,
            boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

}
