USE [master]
GO

/****** Object:  Database [TestDb]    Script Date: 21/06/2016 07:38:14 ******/
CREATE DATABASE [TestDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TestDb.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TestDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TestDb_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TestDb] SET COMPATIBILITY_LEVEL = 120
GO

ALTER DATABASE [TestDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TestDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestDb] SET  MULTI_USER 
GO

ALTER DATABASE [TestDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TestDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestDb] SET  READ_WRITE 
GO

USE master;  
GO  
CREATE DATABASE FileStreamDB  
ON PRIMARY   
    (  
    NAME = FileStreamDB_data   
    ,FILENAME = ''  
    ,SIZE = 10MB  
    ,MAXSIZE = 50MB  
    ,FILEGROWTH = 15%  
    ),  
FILEGROUP FileStreamPhotos CONTAINS FILESTREAM DEFAULT  
    (  
    NAME = FSPhotos  
    ,FILENAME = 'C:\MyFSfolderPhotos' 
, MAXSIZE = 5000 MB  
    ),  
    (  
      NAME = FSPhotos2  
      , FILENAME = 'D:\MyFSfolderPhotos'  
      , MAXSIZE = 10000 MB  
     ),  
FILEGROUP FileStreamResumes CONTAINS FILESTREAM  
    (  
    NAME = FileStreamResumes  
    ,FILENAME = 'C:\MyFSfolderResumes'
    ) 
LOG ON  
    (  
    NAME = FileStream_log  
    ,FILENAME = 'FileStreamDB_log.ldf'
    ,SIZE = 5MB  
    ,MAXSIZE = 25MB  
    ,FILEGROWTH = 5MB  
    )
GO  
ALTER DATABASE ADVENTUREWORKS2012 SET PARTNER FAILOVER;  
GO  

ALTER DATABASE AccountsDb1 SET HADR AVAILABILITY GROUP = AccountsAG;
GO

ALTER DATABASE AdventureWorks 
ADD FILE 
(
    NAME = Test1dat2,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\t1dat2.ndf',
    SIZE = 5MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 5MB

);
GO

ALTER DATABASE AdventureWorks
ADD FILEGROUP Test1FG1;
GO

ALTER DATABASE AdventureWorks 
ADD FILE 
(
    NAME = test1dat3,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\t1dat3.ndf',
    SIZE = 5MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 5MB
),
(
    NAME = test1dat4,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\t1dat4.ndf',
    SIZE = 5MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 5MB
)
TO FILEGROUP Test1FG1;
GO

ALTER DATABASE AdventureWorks 
ADD LOG FILE 
(
    NAME = test1log2,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\test2log.ldf',
    SIZE = 5MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 5MB
),
(
    NAME = test1log3,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\test3log.ldf',
    SIZE = 5MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 5MB
);
GO

ALTER DATABASE AdventureWorks
REMOVE FILE test1dat4;
GO

ALTER DATABASE AdventureWorks 
MODIFY FILE
    (NAME = test1dat3,
    SIZE = 20MB);
GO

ALTER DATABASE AdventureWorks
MODIFY FILE
(
    NAME = Test1dat2,
    FILENAME = N'c:\t1dat2.ndf'
);
GO

ALTER DATABASE tempdb 
MODIFY FILE (NAME = tempdev, FILENAME = 'E:\SQLData\tempdb.mdf');
GO

ALTER DATABASE AdventureWorks 
MODIFY FILEGROUP Test1FG1 DEFAULT;
GO
ALTER DATABASE AdventureWorks 
MODIFY FILEGROUP [PRIMARY] DEFAULT;
GO

ALTER database FileStreamPhotoDB
ADD FILEGROUP TodaysPhotoShoot
CONTAINS FILESTREAM
GO

ALTER database FileStreamPhotoDB
ADD FILE
(
    NAME= 'PhotoShoot1',
    FILENAME = 'C:\Users\Administrator\Pictures\TodaysPhotoShoot.ndf'
)
TO FILEGROUP TodaysPhotoShoot
GO

ALTER DATABASE [dbName] ADD FILEGROUP optimizedDataName CONTAINS MEMORY_OPTIMIZED_DATA
GO

--create database with SNAPSHOT option;
CREATE DATABASE sales_snapshot0600 ON
    ( NAME = SPri1_dat, FILENAME = 'D:\SalesData\SPri1dat_0600.ss'),
    ( NAME = SPri2_dat, FILENAME = 'D:\SalesData\SPri2dt_0600.ss'),
    ( NAME = SGrp1Fi1_dat, FILENAME = 'D:\SalesData\SG1Fi1dt_0600.ss'),
    ( NAME = SGrp1Fi2_dat, FILENAME = 'D:\SalesData\SG1Fi2dt_0600.ss'),
    ( NAME = SGrp2Fi1_dat, FILENAME = 'D:\SalesData\SG2Fi1dt_0600.ss'),
    ( NAME = SGrp2Fi2_dat, FILENAME = 'D:\SalesData\SG2Fi2dt_0600.ss')
AS SNAPSHOT OF Sales;
GO