-- create index
CREATE INDEX i1 ON t1 (col1);
CREATE CLUSTERED INDEX i1 ON d1.s1.t1 (col1);
CREATE UNIQUE INDEX i1 ON t1 (col1 DESC, col2 ASC, col3 DESC);
CREATE UNIQUE INDEX i1 ON t1 (col1 DESC, col2 ASC, col3 DESC);
CREATE NONCLUSTERED INDEX i ON t (c1) INCLUDE (AddressLine1, AddressLine2, City, StateProvinceID);
CREATE NONCLUSTERED INDEX i ON t (c1, c2) WHERE c3 IS NOT NULL;
CREATE CLUSTERED INDEX i ON t (c1) WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1 MINUTES, ABORT_AFTER_WAIT = NONE)), RESUMABLE = ON, MAX_DURATION = 240 MINUTES);
CREATE CLUSTERED INDEX i ON t (c1) WITH (DATA_COMPRESSION = PAGE ON PARTITIONS (1), DATA_COMPRESSION = ROW ON PARTITIONS (2 TO 4, 5 to 7));
CREATE CLUSTERED INDEX i ON t (c1) WITH (XML_COMPRESSION = OFF ON PARTITIONS (1), XML_COMPRESSION = ON ON PARTITIONS (2, 4, 6 TO 8), XML_COMPRESSION = OFF ON PARTITIONS (3, 5));

CREATE NONCLUSTERED INDEX [index_table1] ON [dbo].[table1] ([c1])
WITH (
 PAD_INDEX = OFF,
 FILLFACTOR = 70,
 SORT_IN_TEMPDB = OFF,
 IGNORE_DUP_KEY = OFF,
 STATISTICS_NORECOMPUTE = OFF,
 STATISTICS_INCREMENTAL = OFF,
 DROP_EXISTING = OFF,
 ONLINE = OFF,
 RESUMABLE = OFF,
 MAX_DURATION = 4,
 ALLOW_ROW_LOCKS = OFF,
 ALLOW_PAGE_LOCKS = OFF,
 OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF,
 MAXDOP = 30,
 DATA_COMPRESSION = ROW,
 XML_COMPRESSION = OFF)
ON [PRIMARY]
GO

-- drop index
DROP INDEX tbl.idx_tbl_col;
DROP INDEX IX_ProductVendor_BusinessEntityID ON Purchasing.ProductVendor;

-- alter index
ALTER INDEX ALL ON [t1] REBUILD;
ALTER INDEX ALL ON [dbo].[t1] REBUILD;
ALTER INDEX ALL ON [dbo].[t1] REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON [dbo].[t1] REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON, ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 4 MINUTES, ABORT_AFTER_WAIT = BLOCKERS)), DATA_COMPRESSION = ROW);
ALTER INDEX [ind1] ON [t1] REBUILD;
ALTER INDEX [ind1] ON [dbo].[t1] REBUILD;
ALTER INDEX [ind1] ON [t1] REBUILD PARTITION = 12;
ALTER INDEX [ind1] ON [t1] REBUILD WITH (DATA_COMPRESSION = COLUMNSTORE);
ALTER INDEX [ind1] ON [t1] REBUILD WITH (DATA_COMPRESSION = PAGE);
ALTER INDEX [ind1] ON [t1] REBUILD WITH (XML_COMPRESSION = ON);
ALTER INDEX [ind1] on [t1] REBUILD WITH (ONLINE = ON, MAXDOP = 1, RESUMABLE = ON);
ALTER INDEX [ind1] on [t1] REBUILD WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 240);
ALTER INDEX [ind1] on [t1] REBUILD WITH (MAX_DURATION = 15 MINUTES, DATA_COMPRESSION = ROW ON PARTITIONS (2 TO 5));
ALTER INDEX [ind1] on [t1] REBUILD WITH (DATA_COMPRESSION = ROW ON PARTITIONS (2 TO 5, 3, 4 TO 12));
ALTER INDEX [ind1] ON [dbo].[t1] REBUILD Partition = 5 WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 10 minutes, ABORT_AFTER_WAIT = SELF)));
ALTER INDEX [ind1] ON [t1] REORGANIZE;
ALTER INDEX [ind1] ON [t1] REORGANIZE WITH (COMPRESS_ALL_ROW_GROUPS = ON);
ALTER INDEX [ind1] ON [t1] REORGANIZE PARTITION = 0;
ALTER INDEX [ind1] ON [t1] REORGANIZE PARTITION = 0 WITH (COMPRESS_ALL_ROW_GROUPS = ON);
ALTER INDEX [ind1] ON [dbo].[t1] REORGANIZE WITH (LOB_COMPACTION = ON);
ALTER INDEX [ind1] ON [dbo].[t1] SET (STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = ON, ALLOW_PAGE_LOCKS = ON);
ALTER INDEX [ind1] ON [dbo].[t1] DISABLE;
ALTER INDEX [ind1] on [t1] PAUSE;
ALTER INDEX [ind1] on [t1] RESUME WITH (MAXDOP = 4);
ALTER INDEX [ind1] on [t1] ABORT;
ALTER INDEX [ind1] on [t1] RESUME WITH (MAXDOP = 2, MAX_DURATION = 240 MINUTES, WAIT_AT_LOW_PRIORITY (MAX_DURATION = 10, ABORT_AFTER_WAIT = BLOCKERS));
ALTER INDEX i ON t REBUILD PARTITION = 1 WITH (XML_COMPRESSION = OFF ON PARTITIONS (1), XML_COMPRESSION = ON ON PARTITIONS (2 to 3, 5 to 7));