-- create index
CREATE INDEX i1 ON t1 (col1);
CREATE CLUSTERED INDEX i1 ON d1.s1.t1 (col1);
CREATE UNIQUE INDEX i1 ON t1 (col1 DESC, col2 ASC, col3 DESC);
CREATE UNIQUE INDEX i1 ON t1 (col1 DESC, col2 ASC, col3 DESC);
CREATE NONCLUSTERED INDEX i ON t (c1) INCLUDE (AddressLine1, AddressLine2, City, StateProvinceID);
CREATE NONCLUSTERED INDEX i ON t (c1, c2) WHERE c3 IS NOT NULL;
CREATE CLUSTERED INDEX i ON t (c1) WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1 MINUTES, ABORT_AFTER_WAIT = NONE)), RESUMABLE = ON, MAX_DURATION = 240 MINUTES);
CREATE CLUSTERED INDEX i ON t (c1) WITH (DATA_COMPRESSION = PAGE ON PARTITIONS (1), DATA_COMPRESSION = ROW ON PARTITIONS (2 TO 4, 5 to 7));
CREATE CLUSTERED INDEX i ON t (c1) WITH (XML_COMPRESSION = OFF ON PARTITIONS (1), XML_COMPRESSION = ON ON PARTITIONS (2, 4, 6 TO 8), XML_COMPRESSION = OFF ON PARTITIONS (3, 5));

CREATE NONCLUSTERED INDEX [index_table1] ON [dbo].[table1] ([c1])
WITH (
 PAD_INDEX = OFF,
 FILLFACTOR = 70,
 SORT_IN_TEMPDB = OFF,
 IGNORE_DUP_KEY = OFF,
 STATISTICS_NORECOMPUTE = OFF,
 STATISTICS_INCREMENTAL = OFF,
 DROP_EXISTING = OFF,
 ONLINE = OFF,
 RESUMABLE = OFF,
 MAX_DURATION = 4,
 ALLOW_ROW_LOCKS = OFF,
 ALLOW_PAGE_LOCKS = OFF,
 OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF,
 MAXDOP = 30,
 DATA_COMPRESSION = ROW,
 XML_COMPRESSION = OFF)
ON [PRIMARY]
GO

--create COLUMNSTORE INDEX with ORDER (in 2022 version)
CREATE CLUSTERED COLUMNSTORE INDEX MyOrderedCCI ON d1.s1.c1
ORDER (c1, c2)
WITH (DROP_EXISTING = ON);
GO

CREATE CLUSTERED COLUMNSTORE INDEX cci ON Sales.OrderLines
ORDER (SHIPDATE);

--create COLUMNSTORE INDEX
CREATE CLUSTERED COLUMNSTORE INDEX [idx_table1] ON [dbo].[table1]
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
ON [PRIMARY]
GO

--NONCLUSTERED INDEX with column list
CREATE NONCLUSTERED COLUMNSTORE INDEX [idx_table3] ON [dbo].[table3]
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
ON [PRIMARY]
GO

CREATE NONCLUSTERED COLUMNSTORE INDEX [idx_table4]
ON [dbo].[table3]
(col2, col3)

--NONCLUSTERED INDEX
CREATE COLUMNSTORE INDEX [idx_table6] ON [dbo].[table6] (col1, col2)
WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, DATA_COMPRESSION = COLUMNSTORE)
ON [PRIMARY]
GO

-- drop index
DROP INDEX tbl.idx_tbl_col;
DROP INDEX IX_ProductVendor_BusinessEntityID ON Purchasing.ProductVendor;

-- alter index
ALTER INDEX ALL ON [t1] REBUILD;
ALTER INDEX ALL ON [dbo].[t1] REBUILD;
ALTER INDEX ALL ON [dbo].[t1] REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON [dbo].[t1] REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON, ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 4 MINUTES, ABORT_AFTER_WAIT = BLOCKERS)), DATA_COMPRESSION = ROW);
ALTER INDEX [ind1] ON [t1] REBUILD;
ALTER INDEX [ind1] ON [dbo].[t1] REBUILD;
ALTER INDEX [ind1] ON [t1] REBUILD PARTITION = 12;
ALTER INDEX [ind1] ON [t1] REBUILD WITH (DATA_COMPRESSION = COLUMNSTORE);
ALTER INDEX [ind1] ON [t1] REBUILD WITH (DATA_COMPRESSION = PAGE);
ALTER INDEX [ind1] ON [t1] REBUILD WITH (XML_COMPRESSION = ON);
ALTER INDEX [ind1] on [t1] REBUILD WITH (ONLINE = ON, MAXDOP = 1, RESUMABLE = ON);
ALTER INDEX [ind1] on [t1] REBUILD WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 240);
ALTER INDEX [ind1] on [t1] REBUILD WITH (MAX_DURATION = 15 MINUTES, DATA_COMPRESSION = ROW ON PARTITIONS (2 TO 5));
ALTER INDEX [ind1] on [t1] REBUILD WITH (DATA_COMPRESSION = ROW ON PARTITIONS (2 TO 5, 3, 4 TO 12));
ALTER INDEX [ind1] ON [dbo].[t1] REBUILD Partition = 5 WITH (ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 10 minutes, ABORT_AFTER_WAIT = SELF)));
ALTER INDEX [ind1] ON [t1] REORGANIZE;
ALTER INDEX [ind1] ON [t1] REORGANIZE WITH (COMPRESS_ALL_ROW_GROUPS = ON);
ALTER INDEX [ind1] ON [t1] REORGANIZE PARTITION = 0;
ALTER INDEX [ind1] ON [t1] REORGANIZE PARTITION = 0 WITH (COMPRESS_ALL_ROW_GROUPS = ON);
ALTER INDEX [ind1] ON [dbo].[t1] REORGANIZE WITH (LOB_COMPACTION = ON);
ALTER INDEX [ind1] ON [dbo].[t1] SET (STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = ON, ALLOW_PAGE_LOCKS = ON);
ALTER INDEX [ind1] ON [dbo].[t1] DISABLE;
ALTER INDEX [ind1] on [t1] PAUSE;
ALTER INDEX [ind1] on [t1] RESUME WITH (MAXDOP = 4);
ALTER INDEX [ind1] on [t1] ABORT;
ALTER INDEX [ind1] on [t1] RESUME WITH (MAXDOP = 2, MAX_DURATION = 240 MINUTES, WAIT_AT_LOW_PRIORITY (MAX_DURATION = 10, ABORT_AFTER_WAIT = BLOCKERS));
ALTER INDEX i ON t REBUILD PARTITION = 1 WITH (XML_COMPRESSION = OFF ON PARTITIONS (1), XML_COMPRESSION = ON ON PARTITIONS (2 to 3, 5 to 7));

-- SPATIAL INDEX
CREATE SPATIAL INDEX SIndxgeometry_col1
   ON t1(geometry_col)
   WITH (BOUNDING_BOX = (0, 0, 500, 200));
GO

CREATE SPATIAL INDEX SIndx_geometry_col2
   ON t1(geometry_col)
   USING GEOMETRY_GRID
   WITH (
    BOUNDING_BOX = (xmin=0, ymin=0, xmax=500, ymax=200),
    GRIDS = (LOW, LOW, MEDIUM, HIGH),
    CELLS_PER_OBJECT = 64,
    PAD_INDEX  = ON);
GO

CREATE SPATIAL INDEX SIndx_geometry_col3
   ON t1(geometry_col)
   WITH (
    BOUNDING_BOX = (0, 0, 500, 200),
    GRIDS = (LEVEL_4 = HIGH, LEVEL_3 = MEDIUM));
GO

CREATE SPATIAL INDEX SIndx_geography_col3
   ON t1(geography_col)
   WITH (BOUNDING_BOX = (0, 0, 500, 200),
        GRIDS = (LEVEL_3 = LOW),
        DROP_EXISTING = ON);
GO

CREATE SPATIAL INDEX SIndx_geography_col1
   ON t1(object);
GO

CREATE SPATIAL INDEX SIndx_geography_col2
   ON t1(object)
   USING GEOGRAPHY_GRID
   WITH (
    GRIDS = (MEDIUM, LOW, MEDIUM, HIGH),
    CELLS_PER_OBJECT = 64,
    PAD_INDEX  = ON);
GO

CREATE SPATIAL INDEX SIndx_geography_col3
   ON t1(object)
   WITH (GRIDS = (LEVEL_3 = HIGH, LEVEL_2 = HIGH));
GO