USE AdventureWorks2012;  
GO  
ALTER SCHEMA HumanResources TRANSFER Person.Address;  
GO  
ALTER SCHEMA Person TRANSFER type::Production.TestType ;
GO
ALTER SCHEMA Sales TRANSFER OBJECT::dbo.Region;
GO
USE AdventureWorks2012;  
GO  
CREATE SCHEMA Sprockets AUTHORIZATION Annik;
GO   
CREATE SCHEMA Sales;
GO;

CREATE TABLE Sales.Region
(Region_id int NOT NULL,
Region_Name char(5) NOT NULL)
WITH (DISTRIBUTION = REPLICATE);
GO  
CREATE SCHEMA Production AUTHORIZATION [Contoso\Mary];
GO

ALTER PARTITION SCHEME MyRangePS1  
NEXT USED test5fg;
GO

CREATE PARTITION SCHEME myRangePS1  
AS PARTITION myRangePF1  
ALL TO ( [PRIMARY] );
GO

CREATE PARTITION SCHEME myRangePS4  
AS PARTITION myRangePF4  
TO (test1fg, test2fg, test3fg, test4fg, test5fg)
GO

CREATE PARTITION SCHEME myRangePS3  
AS PARTITION myRangePF3  
ALL TO ( test1fg );
GO

CREATE PARTITION SCHEME myRangePS1
    AS PARTITION myRangePF1
    ALL TO ('PRIMARY') ;
GO