CREATE PUBLICATION alltables FOR ALL TABLES;
CREATE PUBLICATION testpub_default;
CREATE PUBLICATION testpib_ins_trunct WITH (publish = insert);
CREATE PUBLICATION testpub_xxx WITH (foo);
CREATE PUBLICATION testpub_xxx WITH (publish = 'cluster, vacuum');
CREATE PUBLICATION testpub_foralltables FOR ALL TABLES WITH (publish = 'insert');
CREATE PUBLICATION testpub2;
CREATE PUBLICATION testpub3 FOR TABLE testpub_tbl3;
CREATE PUBLICATION testpub4 FOR TABLE ONLY testpub_tbl3;
CREATE PUBLICATION testpub_fortbl FOR TABLE testpub_view;
CREATE PUBLICATION testpub_fortbl FOR TABLE testpub_tbl1, pub_test.testpub_nopk;
ALTER PUBLICATION testpub_default SET (publish = update);
ALTER PUBLICATION testpub_default SET (publish = 'insert, update, delete');
ALTER PUBLICATION testpub_foralltables SET (publish = 'insert, update');
ALTER PUBLICATION testpub_foralltables ADD TABLE testpub_tbl2;
ALTER PUBLICATION testpub_foralltables DROP TABLE testpub_tbl2;
ALTER PUBLICATION testpub_foralltables SET TABLE pub_test.testpub_nopk;
ALTER PUBLICATION testpub_fortbl ADD TABLE testpub_tbl1;
ALTER PUBLICATION testpub_default OWNER TO regress_publication_user2;
ALTER PUBLICATION testpub_default RENAME TO testpub_dummy;
ALTER PUBLICATION testpub_default DROP TABLE pub_test.testpub_nopk;
DROP PUBLICATION testpub3, testpub4;
DROP PUBLICATION testpub2;
COMMENT ON PUBLICATION testpub_default IS 'test publication';
CREATE PUBLICATION myp FOR TABLE ONLY t1, ONLY t2;
CREATE PUBLICATION production_publication FOR TABLE users, departments, TABLES IN SCHEMA production;
CREATE PUBLICATION sales_publication FOR TABLES IN SCHEMA marketing, sales;
CREATE PUBLICATION active_departments FOR TABLE departments WHERE (active IS TRUE);
CREATE PUBLICATION mypublication FOR TABLE users, departments;
ALTER PUBLICATION mypublication SET TABLE users (user_id, firstname, lastname), TABLE departments;
ALTER PUBLICATION production_publication ADD TABLE users, departments, TABLES IN SCHEMA production;
ALTER PUBLICATION sales_publication ADD TABLES IN SCHEMA marketing, sales;