CREATE VIEW v1 AS SELECT 1;
CREATE OR REPLACE VIEW v1 AS select 1;
CREATE TEMP VIEW v1 AS select 1;
CREATE TEMPORARY VIEW v1 AS select 1;
CREATE RECURSIVE VIEW v1 (c1) AS select 1;
CREATE VIEW v1 (c1) AS select 1;
CREATE VIEW v1 WITH (security_barrier) AS select 1;
CREATE VIEW v1 WITH (security_barrier = true) AS select 1;
CREATE VIEW v1 WITH (security_barrier = true, check_option = local) AS select 1;
CREATE VIEW v1 AS select 1 WITH CHECK OPTION;
CREATE VIEW v1 AS select 1 WITH LOCAL CHECK OPTION;
CREATE VIEW v1 AS select 1 WITH CASCADED CHECK OPTION;
CREATE OR REPLACE TEMP RECURSIVE VIEW v1 (c1) WITH (security_barrier) AS select 1 WITH CHECK OPTION;

ALTER VIEW v1 ALTER c1 SET DEFAULT 50;
ALTER VIEW v1 ALTER COLUMN c1 SET DEFAULT 50;
ALTER VIEW v1 ALTER c1 DROP DEFAULT;
ALTER VIEW IF EXISTS v1 ALTER COLUMN c1 DROP DEFAULT;
ALTER VIEW v1 OWNER TO test_user;
ALTER VIEW v1 OWNER TO CURRENT_USER;
ALTER VIEW v1 OWNER TO SESSION_USER;
ALTER VIEW v1 RENAME c1 TO c2;
ALTER VIEW v1 RENAME COLUMN c1 TO c2;
ALTER VIEW v1 RENAME TO v2;
ALTER VIEW v1 SET SCHEMA test_schema;
ALTER VIEW v1 SET (security_barrier);
ALTER VIEW v1 SET (security_barrier = false);
ALTER VIEW v1 SET (security_barrier = false, check_option = local);
ALTER VIEW v1 RESET (security_barrier);
ALTER VIEW v1 RESET (security_barrier, check_option);

DROP VIEW v1;
DROP VIEW IF EXISTS public.v1;
DROP VIEW v1, v2, public.v3;
DROP VIEW v1 CASCADE;
DROP VIEW v1 RESTRICT;
DROP VIEW v1, v2, public.v3 CASCADE;

CREATE MATERIALIZED VIEW public.v1 AS SELECT 1;
CREATE MATERIALIZED VIEW IF NOT EXISTS public.v1 AS SELECT 1;
CREATE MATERIALIZED VIEW v1 (c1) AS SELECT 1;
CREATE MATERIALIZED VIEW v1 USING heap AS SELECT 1;
CREATE MATERIALIZED VIEW v1 WITH (autovacuum_enabled) AS SELECT 1;
CREATE MATERIALIZED VIEW v1 WITH (autovacuum_enabled = false, fillfactor = '70') AS SELECT 1;
CREATE MATERIALIZED VIEW v1 TABLESPACE test_tablespace AS SELECT 1;
CREATE MATERIALIZED VIEW v1 AS SELECT 1 WITH DATA;
CREATE MATERIALIZED VIEW v1 AS SELECT 1 WITH NO DATA;
CREATE MATERIALIZED VIEW IF NOT EXISTS v1(c1) USING heap TABLESPACE test_tablespace AS SELECT 1 WITH NO DATA;

ALTER MATERIALIZED VIEW v1 ALTER COLUMN c1 SET STATISTICS 50;
ALTER MATERIALIZED VIEW v1 ALTER COLUMN c1 SET (n_distinct = -1);
ALTER MATERIALIZED VIEW v1 ALTER COLUMN c1 SET (n_distinct = -1, n_distinct_inherited = -1);
ALTER MATERIALIZED VIEW v1 ALTER COLUMN c1 RESET (n_distinct);
ALTER MATERIALIZED VIEW v1 ALTER COLUMN c1 RESET (n_distinct, n_distinct_inherited);
ALTER MATERIALIZED VIEW v1 ALTER COLUMN c1 SET STORAGE EXTERNAL;
ALTER MATERIALIZED VIEW v1 CLUSTER ON i;
ALTER MATERIALIZED VIEW v1 SET WITHOUT CLUSTER;
ALTER MATERIALIZED VIEW v1 SET (autovacuum_enabled);
ALTER MATERIALIZED VIEW v1 SET (autovacuum_enabled = false);
ALTER MATERIALIZED VIEW v1 SET (autovacuum_enabled = false, fillfactor = 70);
ALTER MATERIALIZED VIEW v1 RESET (autovacuum_enabled);
ALTER MATERIALIZED VIEW v1 RESET (autovacuum_enabled, fillfactor);
ALTER MATERIALIZED VIEW v1 OWNER TO test_user;
ALTER MATERIALIZED VIEW v1 OWNER TO CURRENT_USER;
ALTER MATERIALIZED VIEW v1 OWNER TO SESSION_USER;
ALTER MATERIALIZED VIEW v1 DEPENDS ON EXTENSION ext;
ALTER MATERIALIZED VIEW v1 NO DEPENDS ON EXTENSION ext;
ALTER MATERIALIZED VIEW v1 RENAME c1 TO c2;
ALTER MATERIALIZED VIEW v1 RENAME COLUMN c1 TO c2;
ALTER MATERIALIZED VIEW v1 RENAME TO v2;
ALTER MATERIALIZED VIEW IF EXISTS v1 RENAME TO v2;
ALTER MATERIALIZED VIEW v1 SET SCHEMA test_schema;
ALTER MATERIALIZED VIEW IF EXISTS v1 SET SCHEMA test_schema;
ALTER MATERIALIZED VIEW ALL IN TABLESPACE pg_default SET TABLESPACE new_tablespace;
ALTER MATERIALIZED VIEW ALL IN TABLESPACE pg_default SET TABLESPACE new_tablespace NOWAIT;
ALTER MATERIALIZED VIEW ALL IN TABLESPACE pg_default OWNED BY usr1, usr2 SET TABLESPACE new_tablespace;

DROP MATERIALIZED VIEW v1;
DROP MATERIALIZED VIEW IF EXISTS public.v1;
DROP MATERIALIZED VIEW v1, v2, public.v3;
DROP MATERIALIZED VIEW v1 CASCADE;
DROP MATERIALIZED VIEW v1 RESTRICT;
DROP MATERIALIZED VIEW v1, v2, public.v3 CASCADE;

REFRESH MATERIALIZED VIEW v1;
REFRESH MATERIALIZED VIEW CONCURRENTLY v1;
REFRESH MATERIALIZED VIEW v1 WITH DATA;
REFRESH MATERIALIZED VIEW v1 WITH NO DATA;
REFRESH MATERIALIZED VIEW CONCURRENTLY v1 WITH NO DATA;

-- ALTER MATERIALIZED VIEW SET ACCESS METHOD
ALTER MATERIALIZED VIEW mvtest_tvm SET ACCESS METHOD heap23;

-- Greenplum
CREATE MATERIALIZED VIEW public.test_view AS
	SELECT asdfqwerty.c1
   FROM public.asdfqwerty
WITH DATA DISTRIBUTED RANDOMLY;

CREATE MATERIALIZED VIEW public.test_view1 AS
	SELECT asdfqwerty.c1
   FROM public.asdfqwerty
WITH DATA DISTRIBUTED REPLICATED;

CREATE MATERIALIZED VIEW public.test_view2 AS
	SELECT asdfqwerty.c1
   FROM public.asdfqwerty
WITH DATA DISTRIBUTED BY (c1);


